-- 创建 AI 新闻表
create table public.ai_news (
  id bigint generated by default as identity primary key,
  source text,
  title text,
  link text,
  summary text,
  published timestamp with time zone,
  published_str text,
  fetched_date date, -- 用于日历查询的关键字段
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- 创建 Reddit 热门表
create table public.reddit_demands (
  id bigint generated by default as identity primary key,
  source text,
  title text,
  score int,
  comments int,
  url text,
  permalink text,
  created_utc text,
  fetched_date date, -- 用于日历查询的关键字段
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- 创建索引以加速按日期查询
create index ai_news_fetched_date_idx on public.ai_news (fetched_date);
create index reddit_demands_fetched_date_idx on public.reddit_demands (fetched_date);

-- 开启 Row Level Security (RLS) - 可选，如果只是后端服务访问，可以先关闭或配置策略
alter table public.ai_news enable row level security;
alter table public.reddit_demands enable row level security;

-- 创建简单的读取策略 (允许所有读取)
create policy "Enable read access for all users" on public.ai_news for select using (true);
create policy "Enable read access for all users" on public.reddit_demands for select using (true);

-- 创建简单的插入策略 (允许服务角色插入，如果用 anon key 可能需要开放 insert)
-- 这里假设你使用 service_role key 或者开启了匿名写入 (不推荐生产环境)
-- 为了开发方便，先允许所有 insert
create policy "Enable insert for all users" on public.ai_news for insert with check (true);
create policy "Enable insert for all users" on public.reddit_demands for insert with check (true);